### ISSUE TITLE
Problem connection

### ISSUE THREAD

**Issue by winnie71** [frnmst/gnupot#3]
![schermata1](https://cloud.githubusercontent.com/assets/1334496/8358821/c5042cc8-1b62-11e5-95d5-da30bef1dfcb.png)
forewer...
boo

**Comment by frnmst** [comment]
Try to comment the whole while loop where it says `while [ $(ping ...` in line ~= 270.

**Comment by winnie71** [comment]
I have solved th problem
add a new dependence
in arch or derivetes use 
pacman -S iputils

**Comment by frnmst** [comment]
Added `iputils` in dependencies list. Thank you.
