### ISSUE TITLE
GNUpot connection or auth problem. Retryng...

### ISSUE THREAD

**Issue by winnie71** [frnmst/gnupot#5]
You will have an idea?

![istantanea_2015-07-28_17-35-41](https://cloud.githubusercontent.com/assets/1334496/8937254/7bd6c150-3557-11e5-8a59-69b816f5783f.png)

**Comment by frnmst** [comment]
Try adding `set -x` near the top of `src/gnupot.sh` file. This way you will see how each command is executed and possibly where the problem is.

**Comment by winnie71** [comment]
+ return 0
++ ping -c 1 -s 0 -W 30 79.24.190.67
++ printf 2
+ '[' 2 -ne 0 ']'
+ busyWait
+ notify 'GNUpot connection or auth problem. Retrying...' 2000
+ local 'msg=GNUpot connection or auth problem. Retrying...' ms=2000
+ '[' -n :0.0 ']'
+ notify-send -t 2000 'GNUpot connection or auth problem. Retrying...'
+ return 0
+ updateDNSRecord
+ getAddrByName
+ local 'hostErrMsg=Cannot resolve host name.\n'
+ [[ thepassword.duckdns.org =~ [[:alpha:]] ]]
+ [[ ! thepassword.duckdns.org =~ : ]]
++ getent hosts thepassword.duckdns.org
++ awk ' { print $1 } '
+ gnupotServer=79.24.190.67
+ '[' -z 79.24.190.67 ']'
+ return 0
+ setUpdateableGloblVars
+ SSHCONNECTCMDARGS='-o PasswordAuthentication=no -i /home/xluciano/.config/gnupot/id_rsa_gnupot -C -S /home/xluciano/.config/gnupot/gnupotSSHMasterSocket -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no gnupot@79.24.190.67'
+ SSHMASTERSOCKCMDARGS='-M -o ControlPersist=120m -o PasswordAuthentication=no -i /home/xluciano/.config/gnupot/id_rsa_gnupot -C -S /home/xluciano/.config/gnupot/gnupotSSHMasterSocket -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no gnupot@79.24.190.67 exit'
+ GIT_SSH_COMMAND='ssh -o PasswordAuthentication=no -i /home/xluciano/.config/gnupot/id_rsa_gnupot -C -S /home/xluciano/.config/gnupot/gnupotSSHMasterSocket -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
+ return 0
+ return 0
+ sleep 60

**Comment by frnmst** [comment]
The problem seems to be in the usual `ping` command (line `236`) which returns an exit status of 2 and not 0 as expected. Network problem maybe?

**Comment by winnie71** [comment]
Mysteries of Manjaro, I reinstalled the software "sudo pacman -S iputils" and GNUpot now works perfectly...

**Comment by frnmst** [comment]
Glad to read that. You can try the development version (which hasn't got the `ping` command) like this:

```
cd gnupot
git checkout dev
git pull origin dev
```

Let me know if it works.
Thank you.

**Comment by winnie71** [comment]
When the transition to the dev branch has been successful.
GNUpot works

Thank you.

**Comment by frnmst** [comment]
Thanks for your feedback.
